version: 2
jobs:
  build:
    docker:
      - image: hseeberger/scala-sbt:8u151-2.12.5-1.1.2
    working_directory: ~/workdir
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Clone test project
          working_directory: ~/
          command: |
            (git -C ~/codacy-plugins-test fetch --all && 
              git -C ~/codacy-plugins-test reset --hard origin/master) || 
                git clone git://github.com/codacy/codacy-plugins-test.git ~/codacy-plugins-test
      - restore_cache:
          key: scala-library-dependencies-{{ checksum "build.sbt" }}
      - run:
          name: Prepare docker binary
          command: |
            curl https://download.docker.com/linux/static/stable/x86_64/docker-17.09.1-ce.tgz --output docker.tgz
            tar -xvf docker.tgz
            mv docker/docker /usr/local/bin/docker
            rm -rf docker
      - run: 
          name: Compile test project
          working_directory: ~/codacy-plugins-test
          command: sbt compile
      - run: 
          name: Publish tool docker locally
          working_directory: ~/workdir
          command: sbt 'set version in Docker := "latest"' "set name := \"$CIRCLE_PROJECT_REPONAME\"" docker:publishLocal
      - save_cache:
          key: scala-library-dependencies-{{ checksum "build.sbt" }}
          paths:
            - "~/.ivy2"
            - "~/.m2"
            - "~/.sbt"
            - "~/codacy-plugins-test/target"
            - "~/codacy-plugins-test/project/target"
            - "~/codacy-plugins-test/project/project"
            - "~/workdir/target"
            - "~/workdir/project/target"
            - "~/workdir/project/project"
      - run: 
          name: Test json
          working_directory: ~/codacy-plugins-test
          command: sbt -Dcodacy.tests.ignore.descriptions=true "run-main codacy.plugins.DockerTest json $CIRCLE_PROJECT_REPONAME:latest"
      - run:
          name: Test patterns
          working_directory: ~/codacy-plugins-test
          command: sbt -Dcodacy.tests.noremove=true -Dcodacy.tests.threads=8 "run-main codacy.plugins.DockerTest pattern $CIRCLE_PROJECT_REPONAME:latest"

  deploy:
    docker:
      - image: docker:stable
    steps:
      - setup_remote_docker
      - run:
          name: Publish docker
          command: |
              docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
              docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME
              docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME:1.0.$CIRCLE_BUILD_NUM
              docker push codacy/$CIRCLE_PROJECT_REPONAME

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
